config/routes.rb
Tavern::Application.routes.draw do

  get "about", :to => "pages#about" 

  resources :users
  resources :posts
  resources :comments

  resource :session

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :post
  validates_presence_of :content

  #TODO: save this in the DB?
  def html
    Markdown.render(self.content)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => 'User', :foreign_key => 'user_id', :inverse_of => :posts
  has_many :comments, :dependent => :destroy

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :access

  paginates_per 10

  default_scope order('created_at DESC')
  scope :for, lambda {|current_user| where('access = ? OR access = ? AND user_id = ?', 'restricted', 'private', current_user.id)   }

  def self.defaults
    { access: 'restricted' }
  end

  #TODO: save this in the DB?
  def html
    Markdown.render(self.content)
  end

  def public_access?
    access == 'public'
  end

  def private?
    access == "private"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, :inverse_of => :author
  has_many :comments

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include AuthenticationHelper
  before_filter :ensure_signed_in
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, except: [ :index, :new, :create ]
  respond_to :html, :js

  def edit
  end

  # this works because the Rails has a ActionController::Responder with the logic
  def create
    new_params = comment_params.merge({ user_id: current_user.id })
    @comment = Comment.new(new_params)
    if @comment.save
      flash[:notice] = "Your comment was created" 
    end
    respond_with(@comment.post)
  end

  def update
    if @comment.update_attributes(comment_params)
      flash[:notice] = "Your comment was successfully updated."
    end
    respond_with(@post)
  end

  def destroy
    @comment.destroy
    respond_with(@comment) do |format|
      format.html { redirect_to post_url(@post) }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
      @post = @comment.post
    end

    # Use this method to whitelist the permissible parameters. Example: params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :ensure_signed_in
  def show
    @posts = Post.page(params[:page]).per(1)
    render :template => "posts/index"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [ :index, :new, :create ]
  respond_to :html, :js

  def index
    @posts = Post.for(current_user).page(params[:page])
    respond_with @posts
  end

  def show
    @comments = @post.comments
    @new_comment = @post.comments.new
    respond_with @post
  end

  def new
    @post = Post.new Post.defaults
    respond_with @post
  end

  def edit
  end

  # this works because the Rails has a ActionController::Responder with the logic
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Your post was created" 
    end
    respond_with(@post)
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Your post was successfully updated."
    end
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post) do |format|
      format.html { redirect_to posts_url }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Use this method to whitelist the permissible parameters. Example: params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def post_params
      params.require(:post).permit(:title, :content, :access)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :ensure_signed_in

  def new
    response.headers['WWW-Authenticate'] = Authentication.create_new_auth_headers(session_url)
    head 401
  end

  def create
    auth = Authentication.new(request)
    if auth.requested?
      if auth.authenticated?
        session[:user_id] = auth.user.id
        redirect_to(session[:redirect_to] || root_path)
      else
        render :action => 'problem'
      end
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @posts = user.posts.for(current_user).page(params[:page])
    render 'posts/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
  def signed_in?
    !session[:user_id].nil?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
    #This can happen when we delete an user from the DB
    if @current_user.nil?
      session[:user_id] = nil
      ensure_signed_in
    end
    @current_user
  end

  def ensure_signed_in
    unless signed_in?
      session[:redirect_to] = request.original_url
      redirect_to(new_session_path)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Tavern</title>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">  
    <div class="navbar-inner">  
      <div class="container-fluid">  
        <ul class="nav">  
          <li>
            <%= link_to 'The tavern', root_path, :class => 'brand' %> 
          </li>
          <li>
            <%= link_to 'About', about_path %> 
          </li>
        </ul>  
        <ul class="nav pull-right">  
          <li>
            <%= link_to 'New post', new_post_path, :class =>"btn" %>
          </li>
        </ul>
      </div>  
    </div>  
  </div>   

  <div class="container-fluid" id="contents">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_comment.html.erb
<% unless comment.id.nil? %>
  <%= content_tag_for(:article, comment) do |comment_data| %>
    <% present comment_data do |comment| %>
      <p class='row user_name'>
      <%= comment.author_says %>
      </p>
      <p class='row comment'>
      <%= comment.html %>
      </p>
      <div class='row'>
        <div class='align-right'>
          <%= comment.actions_for(current_user) %>
       </div>
      </div>
    <% end %>
  <% end%>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %><br />
  <%= f.text_field :title, :required => true, :class => 'span6' %>
  <div class='row'>
    <%= f.label :content %><br />
    <%= f.text_area :content, :required => true, :class=> 'span10 input-xlarge', :rows => 15 %><br/>
    Write your post using <a href="https://gist.github.com/raw/976172/70f1e0db278340bd8167c98fb880979b4571e847/gistfile1.md">Markdown</a>
  </div>
  <div class='row'>
    <%= f.radio_button 'access', 'private' %>
     Private access. This is a draft only visible by you. <br/>
    <%= f.radio_button 'access', 'restricted' %>
    Restricted access. Visible to all the logged in users.<br/>
    <% if TAVERN_CONFIG.public_access? %>
      <%= f.radio_button 'access', 'public' %>
      Public access. Visible to all user, do not require log in. <br/>
    <% end %>
  </div>
  <div class='btn-toolbar'>
    <%= f.submit :class=>'btn btn-primary' %>
    <%= link_to 'Cancel', :back, :class =>'btn' %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<div id='posts'>
  <%= render posts %>
</div>

<div class="paginate hidden">
  <%= paginate posts, :remote => true %>
</div>

app/views/posts/_new_comment.html.erb
<%= form_for(@new_comment) do |f| %>
  <% if @new_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @new_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <%= f.label :content %><br />
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.text_area :content, :required => true, :class=> 'span8 input-xlarge', :rows => 6 %><br/>
    Write your post using <a href="https://gist.github.com/raw/976172/70f1e0db278340bd8167c98fb880979b4571e847/gistfile1.md">Markdown</a>
  </div>
  <div class='btn-toolbar'>
    <%= f.submit :class=>'btn btn-primary' %>
    <%= link_to 'Cancel', :back, :class =>'btn' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p id="notice"><%= notice %></p>
<%= content_tag_for(:article, post) do |post_data| %>
  <% present post_data do |post| %>
    <header>
      <h1> <%= link_to post.title, post_data %> </h1>
    </header>
    <p class='row post'>
      <%= post.html %>
    </p>
    <footer class="row align-right">  
      <%= post.information %>
      <%= post.access_info %>
    </footer>
    <div class='row'>
      <div class='align-right'>
        <%= post.actions_for(current_user) %>
     </div>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %>

app/views/posts/index.html.erb
<div class="hero-unit">
  <div class="row">
    <%= current_user.first_name %>, welcome to
  </div>
  <h1 class="row">The tavern</h1>
  <div class="pull-right row">where 1+1 = 10</div>
</div>
<%= render 'posts/list', posts: @posts %>

app/views/posts/index.js.erb
$("<%= j(render @posts) %>").appendTo($("#posts"))
$(".paginate").html( "<%= j(  paginate @posts, :remote => true) %>")

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render :partial => @post %>
<%= render :partial => 'comment', :collection=> @comments %>
<%= render :partial => 'new_comment', :locals => {:comment => @new_comment} %>